In [1]:
%reload_ext autoreload

In [2]:
%autoreload 2

In [3]:
from PIL import Image

In [4]:
from matplotlib import pyplot as plt

In [5]:
import numpy as np

In [6]:
from glob import glob

In [7]:
from dataset import ObjectsDataset

In [8]:
ds = ObjectsDataset('/Users/yehyaa/Downloads/dataset/')

In [9]:
iterator = ds.batch_training_triplets(batch_size=8)

In [10]:
first_batch = next(iterator)

In [11]:
import tensorflow as tf
import numpy as np

In [12]:
from models.features import Features

In [27]:
net = Features()

In [35]:
#initialize
init = tf.initialize_all_variables()
with tf.Session() as sess:
    sess.run(init)
    anchor_feats, puller_feats, pusher_feats, loss = net.evaluate_triplet(
        first_batch['anchor'],
        first_batch['puller'],
        first_batch['pusher'],
        session=sess
    )

[[8.3885908e-02 2.5596880e+03 2.5597720e+03]
 [2.4244505e-01 1.2487957e+04 1.2488199e+04]
 [0.0000000e+00 1.3230007e+03 1.3230007e+03]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 7.4776923e+02 7.4776923e+02]
 [0.0000000e+00 2.5459193e+02 2.5459193e+02]
 [0.0000000e+00 4.7085938e+03 4.7085938e+03]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]]


In [34]:
print(loss)

[2200.2551  3431.3726   748.17786    0.      1398.9423   244.8122
 6138.2363     0.     ]
